version: '1.0'

services:
  db:
    container_name: mysql_db
    image: mysql:latest # mysql:8
    restart: always
    ports: 
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - sql-db:/var/lib/mysql
  
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    profiles:
      - debug
    restart: always
    ports:
      - 5050:80

volumes:
  sql-db: